spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: QWERTY
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create # update - создает один раз, сбрасывает при изменении, create - каждый раз при запуске пересдает таблицы, сбрасывая содержимое
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
